```javascript
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navbar}>
        <a href="/docs">Docs</a>
        <a href="/learn">Learn</a>
        <a href="/templates">Templates</a>
        <a href="/deploy">Deploy</a>
      </nav>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to the <a href="https://nextjs.org">Next.js</a> frontend!.
          </p>
          <div className={styles.logo}>
            <Image src="/next.svg" alt="Next.js Logo" width={64} height={64} />
          </div>
        </div>
      </main>
    </>
  )
}
```