```diff
diff --git a/src/pages/index.js b/src/pages/index.js
index aa5d5a1..8df6eb0 100644
--- a/src/pages/index.js
+++ b/src/pages/index.js
@@ -9,6 +9,16 @@ const inter = Inter({ subsets: ['latin'] })
 export default function Home() {
   return (
     <>
+      <nav>
+        <a href="/docs">Docs</a>
+        <a href="/learn">Learn</a>
+        <a href="/templates">Templates</a>
+        <a href="/deploy">Deploy</a>
+      </nav>
+
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
```