```diff
--- a/src/pages/index.js
+++ b/src/pages/index.js
@@ -8,7 +8,21 @@
   return (
     <>
       <Head>
-        <title>Create Next App</title>
+        <title>Sample Next.js App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
+      <nav>
+        <ul>
+          <li>
+            <a href="https://nextjs.org/docs">Docs</a>
+          </li>
+          <li>
+            <a href="https://nextjs.org/learn">Learn</a>
+          </li>
+          <li>
+            <a href="https://vercel.com/templates?framework=next.js">Templates</a>
+          </li>
+          <li>
+            <a href="https://vercel.com/new">Deploy</a>
+          </li>
+        </ul>
+      </nav>
       <main className={styles.main}>
```