import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li><a href="/docs">Docs</a></li>
            <li><a href="/learn">Learn</a></li>
            <li><a href="/template">Template</a></li>
            <li><a href="/links">Links</a></li>
          </ul>
        </nav>
      </header>
      <main className={styles.main}>
        ...
      </main>
    </>
  )
}